#!/usr/bin/env python
# coding=utf-8
# [IMPORTANT][WARNING] DO NOT DELETE THE 'COMMENTS' ABOVE!! -by ethy.
# The Chinese comments are generated by the inc.
# The English comments are generated by the user.


import rospy

from geometry_msgs.msg import Twist

import sys, select, termios, tty
maxLinearv = 0.8# max linear velosity(the threshold is infact 0.9 in the real system.
minLinearv = -0.8
maxAngularv = 1.57# max angular velosity
minAngularv = -maxAngularv
steps = 0.03


#获取键值函�?
def getKey():
    tty.setraw(sys.stdin.fileno())
    rlist, _, _ = select.select([sys.stdin], [], [], 0.1)
    if rlist:
        key = sys.stdin.read(1)
    else:
        key = ''

    termios.tcsetattr(sys.stdin, termios.TCSADRAIN, settings)
    return key


#主函�?
if __name__=="__main__":
    settings = termios.tcgetattr(sys.stdin) #获取键值初始化，读取终端相关属�?
    
    rospy.init_node('turtlebot_teleop', anonymous = True) #创建ROS节点
    pub = rospy.Publisher('mcmd_vel', Twist, queue_size=5) #创建速度话题发布者，'~cmd_vel'='节点�?/cmd_vel'
    rate = rospy.Rate(4) # set the frequency. for example, this means the rospy will sleep 250ms each iteration.

    vx = 0.0
    wz = 0.0
    twist = Twist() #创建ROS速度话题变量
    while not rospy.is_shutdown():
        key = getKey() #获取键�?
        if key == 'w':
            # increase the speed.
            # The speed is added by 'steps'
            # If the speed is larger than maxLinearv, vx will be maxLinearv.
            vx = min(maxLinearv, vx+steps)
        elif key == 'a':
            # This is used to control the ANGULAR SPEED of the vehicle!
            # see readme.md ples.
            wz = min(maxAngularv, wz+steps)
        elif key == 'd':
            wz = max(minAngularv, wz-steps)
        elif key == 's':
            # decrease the speed.
            vx = max(minLinearv, vx-steps)
        twist.linear.x = vx
        twist.angular.z = wz
        pub.publish(twist)
        print('published.')
        rate.sleep()# sleep 250ms, according to our setting.
    twist.linear.x = 0
    twist.angular.z = 0
    


